### ISSUE TITLE
Using a ${localEnv:VARNAME} syntax in build.args causes

### ISSUE THREAD

**Issue by ross-p-smith** [stuartleeks/devcontainer-build-run#102]
In my devcontainer.json I have a build arg that pulls in a localEnv from my host.  

```
		"args": {
			// To ensure that the group ID for the docker group in the container
			// matches the group ID on the host, add this to your .bash_profile on the host
			// 		export DOCKER_GROUP_ID=$(getent group docker | awk -F ":" '{ print $3 }')
			"DOCKER_GROUP_ID": "${localEnv:DOCKER_GROUP_ID:-1001}"
		}
```
When this build arg gets passed into docker, it is output as
```
DOCKER_GROUP_ID=$***localEnv:DOCKER_GROUP_ID:-1001***
```
This causes problems later on as the string literal is not interpolated.
```
#12 0.064 groupadd: invalid group ID '$***localEnv:DOCKER_GROUP_ID:-1001***
```

**Comment by stuartleeks** [comment]
Ouch! Apologies - the env handling isn't currently aware of the syntax for setting default values like that! I'll take a look at that.

**Comment by stuartleeks** [comment]
In the meantime, I think that [this script for installing docker](https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docker-debian.sh) might handle the scenario you are interested in without requiring you to set the `DOCKER_GROUP_ID` in `devcontainer.json`

**Comment by stuartleeks** [comment]
@ross-p-smith - based on our discussion, it looks like this three-part form isn't supported in dev containers. Are you ok with me closing this issue?
