### ISSUE TITLE
Feature: Support mounts in devcontainer.json

### ISSUE THREAD

**Issue by stuartleeks** [stuartleeks/devcontainer-build-run#30]
Q: what should happen for bind mounts that reference folders that don't exist on the host?

**Comment by stuartleeks** [comment]
Oops - the config value was added in the referenced PR but not the implementation. Re-opening!

**Comment by jsburckhardt** [comment]
Hi folks, I had a situation in which the mount broke my pipeline. I'm currently doing a read only bind of  ~/.ssh and mounting a volume that is used for storing the cli history... when I try to build it in AzDO it fails saying that there is no .ssh ... that is expected ... is there a way to disable mounts?

```bash
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /home/vsts/.ssh.
```
cheers,

Juan
