### ISSUE TITLE
Feature: Support docker-from-docker for dev containers with non-root user

### ISSUE THREAD

**Issue by stuartleeks** [stuartleeks/devcontainer-build-run#63]
If you configure a container to use a non-root user, then attempting to build a docker image inside the dev container (i.e. by mounting the host's `/var/run/docker.sock` in the container), gives a permission denied error running `docker build`. Using `sudo docker build` results in a `docker not found` error because the `docker` CLI was installed as the non-root user.

It would be good to look at how to make this scenario work with the action/task.

**Comment by stuartleeks** [comment]
cc @lawrencegripper

**Comment by lawrencegripper** [comment]
I look at doing something similar a while back when using Linux as my main dev machine. I played around with using user namespace mapping to try and align the UID and GroupID of the non-root using in the container with the current user on the host: https://docs.docker.com/engine/security/userns-remap/

I'm not entirely sure why this didn't work but I do remember I gave up after a bit.

**Comment by stuartleeks** [comment]
Ah yes - I think it will need to do that. Then once the UID & GID of the container user match the host user, I think it will also need to ensure that there is a `docker` group in the container with the same ID as the `docker` group on the host (as [here](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/docker-from-docker#enabling-non-root-access-to-docker-in-the-container))

**Comment by stuartleeks** [comment]
I think this would also make it possible to remove the `chown` 'workaround' [here](https://github.com/stuartleeks/devcontainer-build-run/blob/50291aaf2c4d480d868373014f54b44ba7965469/common/src/docker.ts#L123) which would be a nice benefit :-)

**Comment by stuartleeks** [comment]
Thoughts:
- check `/etc/passwd` on the host to get the host user's UID/GID
- check `/etc/passwd` in the container to get the container user's UID/GID
- if the UID/GID doesn't match then update
- check `/etc/group` on the host to get the `docker` group ID on the host
- check `/etc/group` in the container to get the `docker` group ID in the container 
- if the group IDs don't match then update

Notes:
- I think that both GitHub and AzDO hosts use the `docker` group to secure the docker socket. Could extend this by checking the ownership of the socket
- Need to think what to do if there's a clash of IDs. E.g. if the host `docker` group ID matches a different group ID in the container

**Comment by stuartleeks** [comment]
### Proposal
