### ISSUE TITLE
Delete container on failure

### ISSUE THREAD

**Issue by jjcollinge** [stuartleeks/devcontainer-build-run#92]
When a run command in a devcontainer fails - I believe I am seeing evidence it is not cleaned up. For temporary/hosted build agents this if fine but for dedicated build agents this causes a clash in container name on subsequent runs. This manifests in the error: `Error response from daemon: Conflict. The container name "/guacdev" is already in use`. I haven't been able to confirm this is the case as I don't have access to the build agent today but will verify next week and confirm.

**Comment by stuartleeks** [comment]
Ah, good point. So far my testing has been on hosted agents so I haven't hit this.

My initial thought is to run the container with the --rm switch to automatically clean up the container. Would that work for your scenario?

**Comment by jjcollinge** [comment]
Yes that should work I think!

**Comment by stuartleeks** [comment]
I've had a quick look through the code and I don't believe that it is setting a name for the container when it runs it, so I think it should be getting a different name each time it runs. I think it still makes sense to add the `--rm` when running to help with docker housekeeping, but I'm not sure where the name conflict is coming from.

Is `guacdev` the `imageName` you're passing to the task?

**Comment by jjcollinge** [comment]
Having a quick scan, looks like in this case it's defined as a run arg in devcontainer.json so it'll use a consistent name.

**Comment by stuartleeks** [comment]
Ah - that would explain it! Testing the `--rm` change in #94 

Unrelated, I'd be interested in the motivation for setting the name in the `runArgs` 😄

**Comment by stuartleeks** [comment]
#94 is merged - can you test and let me know if that resolves this issue for you?

**Comment by jjcollinge** [comment]
Thanks @stuartleeks, I'll let you know once tested - regarding the motivation I have no idea :P I'll ask the devcontainer author :D.

**Comment by jjcollinge** [comment]
The fix #94 fixes this as long as no existing image with the desired name already exists on the machine - if this is the case, just delete that named image and runs from then on should work. Thanks @stuartleeks.
